### ISSUE TITLE
Enable Automatic Crash Report

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#17]
Enable automatic crash report, e.g. Crashlytics.

**Comment by seanwu1105** [comment]
The [capacitor-community/firebase-crashlytics](https://github.com/capacitor-community/firebase-crashlytics) plugin is actively maintained. However, there are two disadvantages:

### Disadvantages

#### Instantiation Error

A fatal exception would occur when the app gets installed the first time on an Android device.

```
Fatal Exception: java.lang.InstantiationError: com.google.firebase.iid.zzbe
       at com.google.firebase.messaging.zzc.onBind(com.google.firebase:firebase-messaging@@20.1.2:11)
       at android.app.ActivityThread.handleBindService(ActivityThread.java:3734)
       at android.app.ActivityThread.access$1400(ActivityThread.java:200)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1733)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:7124)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)
```

This exception will not occur after the first time opening the app.

#### Log Crash Reports Manually

Unlike the native Android environment, the plugin does NOT send the crash report automatically when there is a runtime exception in Angular. Developers have to call `crash()` to trigger the logger of Crashlytics. Thus, why don't we just catch the expected error?

``` ts
FirebaseCrashlytic.crash({
  message: "This is a crash message.",
});
```

#### Community Support

The plugin is supported and maintained by the community.

### Advantages

Still, there are advantages to adopt this plugin.

#### Easy to Opt-In in Runtime

The plugin provides methods to enable and disable the crash reports. Thus, we do not need to worry about the GDPR limitations.

``` ts
FirebaseCrashlytics.setEnabled({
  enabled: false,
});
```

#### It WORKS on My Machine

Yes, it works. Partially.

**Comment by seanwu1105** [comment]
[Sentry](https://sentry.io/welcome/) could be a feasible solution. It supports runtime error capture with [Angular](https://sentry.io/for/angular2/).

**Comment by seanwu1105** [comment]
The AppCenter might be a good option: https://github.com/microsoft/appcenter-sdk-cordova/issues/89

**Comment by seanwu1105** [comment]
Wait for the first release of [sentry-capacitor](https://github.com/getsentry/sentry-capacitor).

**Comment by scott-dt** [comment]
210429 setting 有開關 可開啟關閉 新安裝時為關閉狀態確認  但在開啟時沒有跳任何警語或提示
